#!/bin/bash
# EVENT System - Codespace Quick Links
# Generated: November 14, 2025

echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                    EVENT SYSTEM - REMOTE ACCESS GUIDE                        ║"
echo "║                  (GitHub Codespaces - fluffy-fiesta-jj7rrx6x6jr5hjj5g)       ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ STATUS: All 10 services running and accessible remotely"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 PRIMARY SERVICES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 API Server & Documentation"
echo "   Remote: https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev"
echo "   Docs:   https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/api/docs"
echo "   Local:  http://localhost:8000"
echo "   Status: ✅ FastAPI Backend - Production Grade"
echo ""
echo "🎨 Dashboard (React)"
echo "   Remote: https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-3000.app.github.dev"
echo "   Local:  http://localhost:3000"
echo "   Status: ✅ Real-time Mission Control"
echo ""
echo "💾 MinIO Console (S3 Storage)"
echo "   Remote: https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-9002.app.github.dev"
echo "   Local:  http://localhost:9002"
echo "   User:   admin"
echo "   Pass:   adminpassword"
echo "   Status: ✅ Evidence & Model Storage"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 CREDENTIALS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "API Authentication (default):"
echo "   Username: admin"
echo "   Password: Event@2025!"
echo "   ⚠️  CHANGE IN PRODUCTION!"
echo ""
echo "MinIO Access:"
echo "   Username: admin"
echo "   Password: adminpassword"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 SERVICE STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Core Services:"
echo "   ✅ PostgreSQL + PostGIS   (localhost:5432)"
echo "   ✅ Redis Cache             (localhost:6379)"
echo "   ✅ MQTT Broker             (localhost:1883)"
echo "   ✅ MinIO S3 Storage        (localhost:9000)"
echo ""
echo "Application Services:"
echo "   ✅ FastAPI Backend         (port 8000)"
echo "   ✅ React Dashboard         (port 3000)"
echo "   ✅ Celery Scheduler        (background)"
echo "   ✅ Celery Beat             (task scheduling)"
echo "   ✅ UAV Simulator           (MQTT telemetry)"
echo "   ✅ Edge Inference (YOLOv8) (detection service)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Open API Documentation"
echo "    https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/api/docs"
echo ""
echo "2️⃣  Open Dashboard"
echo "    https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-3000.app.github.dev"
echo ""
echo "3️⃣  Test Health"
echo "    curl https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/health"
echo ""
echo "4️⃣  View Complete Status"
echo "    cat /workspaces/EVENT/SYSTEM_LIVE_STATUS.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 USEFUL COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check Service Status:"
echo "   docker-compose ps"
echo ""
echo "View Logs:"
echo "   docker-compose logs -f api           # API logs"
echo "   docker-compose logs -f dashboard     # Dashboard logs"
echo "   docker-compose logs -f scheduler     # Scheduler logs"
echo ""
echo "Database Access:"
echo "   docker exec -it event_postgres psql -U mvp -d mvp"
echo ""
echo "Redis CLI:"
echo "   docker exec -it event_redis redis-cli"
echo ""
echo "MQTT Test:"
echo "   docker exec event_mosquitto mosquitto_sub -t 'test' -C 1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 API EXAMPLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo \"Health Check:\"
echo '   curl https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/health'
echo ""
echo \"System Stats:\"
echo '   curl https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/api/v1/stats'
echo ""
echo \"Version Info:\"
echo '   curl https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/api/version'
echo ""
echo \"List UAVs (requires auth):\"
echo '   curl -H \"Authorization: Bearer TOKEN\" \'
echo '     https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/api/v1/uavs'
echo ""
echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"
echo \"📞 TROUBLESHOOTING\"
echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"
echo \"\"
echo \"Services won't start?\"
echo \"   docker-compose down && docker-compose up -d\"
echo \"\"
echo \"Need to rebuild?\"
echo \"   docker-compose build --no-cache api\"
echo \"\"
echo \"Check resource usage:\"
echo \"   docker stats\"
echo \"\"
echo \"Full documentation:\"
echo \"   - /workspaces/EVENT/README.md\"
echo \"   - /workspaces/EVENT/ARCHITECTURE.md\"
echo \"   - /workspaces/EVENT/SYSTEM_LIVE_STATUS.md\"
echo \"   - /workspaces/EVENT/CODESPACE_ACCESS.md\"
echo \"\"
echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"
echo \"✨ System Ready for Remote Access!\"
echo \"\"
echo \"👉 Start with: https://fluffy-fiesta-jj7rrx6x6jr5hjj5g-8000.app.github.dev/api/docs\"
echo \"\"
