# Model Registry for UAV-Satellite Event Analysis

models:
  - name: yolov8n-detection
    version: "8.0.0"
    type: object_detection
    format: onnx
    path: /app/models/yolov8n.onnx
    input_shape: [1, 3, 640, 640]
    classes:
      - person
      - bicycle
      - car
      - motorcycle
      - airplane
      - bus
      - train
      - truck
      - boat
      - traffic light
      - fire hydrant
      - stop sign
      - parking meter
      - bench
      - bird
      - cat
      - dog
      - horse
      - sheep
      - cow
      - elephant
      - bear
      - zebra
      - giraffe
      - backpack
      - umbrella
      - handbag
      - tie
      - suitcase
      - frisbee
      - skis
      - snowboard
      - sports ball
      - kite
      - baseball bat
      - baseball glove
      - skateboard
      - surfboard
      - tennis racket
      - bottle
      - wine glass
      - cup
      - fork
      - knife
      - spoon
      - bowl
      - banana
      - apple
      - sandwich
      - orange
      - broccoli
      - carrot
      - hot dog
      - pizza
      - donut
      - cake
      - chair
      - couch
      - potted plant
      - bed
      - dining table
      - toilet
      - tv
      - laptop
      - mouse
      - remote
      - keyboard
      - cell phone
      - microwave
      - oven
      - toaster
      - sink
      - refrigerator
      - book
      - clock
      - vase
      - scissors
      - teddy bear
      - hair drier
      - toothbrush
    confidence_threshold: 0.5
    nms_threshold: 0.45
    metadata:
      description: "YOLOv8 Nano model for real-time object detection"
      author: "Ultralytics"
      license: "AGPL-3.0"
      use_cases:
        - person_detection
        - vehicle_detection
        - general_surveillance

  - name: yolov8s-detection
    version: "8.0.0"
    type: object_detection
    format: onnx
    path: /app/models/yolov8s.onnx
    input_shape: [1, 3, 640, 640]
    classes:
      # Same as yolov8n
    confidence_threshold: 0.6
    nms_threshold: 0.45
    metadata:
      description: "YOLOv8 Small model with better accuracy"
      author: "Ultralytics"
      license: "AGPL-3.0"

deployment:
  default_model: yolov8n-detection
  device: cpu  # cpu, cuda, tensorrt
  batch_size: 1
  max_concurrent_requests: 4
  
  optimization:
    enable_tensorrt: false
    precision: fp16  # fp32, fp16, int8
    
  preprocessing:
    resize_method: letterbox
    normalize: true
    mean: [0.0, 0.0, 0.0]
    std: [255.0, 255.0, 255.0]
    
  postprocessing:
    max_detections: 100
    filter_classes:  # Only detect these classes (empty = all)
      - person
      - car
      - truck
      - bus
      - motorcycle

monitoring:
  enable_metrics: true
  log_predictions: true
  save_failed_inferences: true
